"""Ajout table token_blocklist

Revision ID: 68edddb4730d
Revises: 
Create Date: 2026-07-16 11:16:11.852583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68edddb4730d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('revoque_le', sa.DateTime(), nullable=False),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('titulaire_classe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_titulaire_classe_annee'))

    op.drop_table('titulaire_classe')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_note'))

    op.drop_table('note')
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_parent_email'))

    op.drop_table('parent')
    with op.batch_alter_table('creneau_horaire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_creneau_ordre'))

    op.drop_table('creneau_horaire')
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_eleve_matricule_etablissement'))

    op.drop_table('eleve')
    with op.batch_alter_table('matiere_classe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_matiere_classe'))

    op.drop_table('matiere_classe')
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inscription'))

    op.drop_table('inscription')
    op.drop_table('paiement')
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_discipline'))

    op.drop_table('discipline')
    with op.batch_alter_table('matiere', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_matiere_groupe'))

    op.drop_table('matiere')
    op.drop_table('tranche_paiement')
    with op.batch_alter_table('horaire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_horaire_matiere_classe_creneau'))

    op.drop_table('horaire')
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_enseignant_email'))

    op.drop_table('enseignant')
    op.drop_table('groupe_matiere')
    with op.batch_alter_table('annee_scolaire', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint(batch_op.f('fk_annee_scolaire_etablissement'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'etablissement', ['etablissement_id'], ['id'])
        batch_op.drop_column('date_fin')
        batch_op.drop_column('date_debut')

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classe_cycle'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classe_etablissement'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cycle', ['cycle_id'], ['id'])
        batch_op.create_foreign_key(None, 'etablissement', ['etablissement_id'], ['id'])

    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etablissement_id', sa.Integer(), nullable=False))
        batch_op.alter_column('ordre',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint('uq_cycle_etablissement_ordre', ['etablissement_id', 'ordre'])
        batch_op.create_foreign_key(None, 'etablissement', ['etablissement_id'], ['id'])

    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sequence_trimestre'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trimestre', ['trimestre_id'], ['id'])

    with op.batch_alter_table('trimestre', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trimestre_annee_scolaire'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'annee_scolaire', ['annee_scolaire_id'], ['id'])

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doit_changer_mdp', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('mdp_expire_le', sa.DateTime(), nullable=True))
        batch_op.alter_column('actif',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('fk_utilisateur_etablissement'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_utilisateur_role'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'etablissement', ['etablissement_id'], ['id'])
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_utilisateur_role'), 'role', ['role_id'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_utilisateur_etablissement'), 'etablissement', ['etablissement_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('actif',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('mdp_expire_le')
        batch_op.drop_column('doit_changer_mdp')
        batch_op.drop_column('refresh_token_hash')

    with op.batch_alter_table('trimestre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trimestre_annee_scolaire'), 'annee_scolaire', ['annee_scolaire_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sequence_trimestre'), 'trimestre', ['trimestre_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_cycle_etablissement_ordre', type_='unique')
        batch_op.alter_column('ordre',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('etablissement_id')

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_classe_etablissement'), 'etablissement', ['etablissement_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_classe_cycle'), 'cycle', ['cycle_id'], ['id'], onupdate='CASCADE')

    with op.batch_alter_table('annee_scolaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_debut', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annee_scolaire_etablissement'), 'etablissement', ['etablissement_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('groupe_matiere',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('libelle', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enseignant',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name=op.f('fk_enseignant_etablissement'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_enseignant_email'), ['email'], unique=True)

    op.create_table('horaire',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('matiere_classe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('annee_scolaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jour_semaine', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('creneau_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('salle', mysql.VARCHAR(length=30), nullable=True),
    sa.CheckConstraint("`jour_semaine` in ('Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi')", name=op.f('ck_horaire_jour')),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], name=op.f('fk_horaire_annee_scolaire'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creneau_id'], ['creneau_horaire.id'], name=op.f('fk_horaire_creneau'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['matiere_classe_id'], ['matiere_classe.id'], name=op.f('fk_horaire_matiere_classe'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('horaire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_horaire_matiere_classe_creneau'), ['matiere_classe_id', 'jour_semaine', 'creneau_id', 'annee_scolaire_id'], unique=True)

    op.create_table('tranche_paiement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('annee_scolaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('libelle', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('montant_attendu', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date_limite', sa.DATE(), nullable=True),
    sa.CheckConstraint('`montant_attendu` > 0', name=op.f('ck_tranche_montant_positif')),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], name=op.f('fk_tranche_paiement_annee_scolaire'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('matiere',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('libelle', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('groupe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupe_matiere.id'], name=op.f('fk_matiere_groupe'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('matiere', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_matiere_groupe'), ['libelle', 'groupe_id'], unique=True)

    op.create_table('discipline',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inscription_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sequence_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('absences_justifiees', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('absences_non_justifiees', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('retards', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('exclusions', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], name=op.f('fk_discipline_inscription'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], name=op.f('fk_discipline_sequence'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_discipline'), ['inscription_id', 'sequence_id'], unique=True)

    op.create_table('paiement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inscription_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tranche_paiement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('montant_verse', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date_paiement', sa.DATE(), nullable=True),
    sa.Column('mode_paiement', mysql.VARCHAR(length=30), nullable=True),
    sa.CheckConstraint('`montant_verse` > 0', name=op.f('ck_paiement_montant_positif')),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], name=op.f('fk_paiement_inscription'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tranche_paiement_id'], ['tranche_paiement.id'], name=op.f('fk_paiement_tranche_paiement'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inscription',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('eleve_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('classe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('annee_scolaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_inscription', sa.DATE(), nullable=True),
    sa.Column('statut', mysql.VARCHAR(length=30), server_default=sa.text("'Actif'"), nullable=False),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], name=op.f('fk_inscription_annee_scolaire'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], name=op.f('fk_inscription_classe'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], name=op.f('fk_inscription_eleve'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inscription'), ['eleve_id', 'classe_id', 'annee_scolaire_id'], unique=True)

    op.create_table('matiere_classe',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('classe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('matiere_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('enseignant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coefficient', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], name=op.f('fk_matiere_classe_classe'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], name=op.f('fk_matiere_classe_enseignant'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], name=op.f('fk_matiere_classe_matiere'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('matiere_classe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_matiere_classe'), ['classe_id', 'matiere_id'], unique=True)

    op.create_table('eleve',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('matricule', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('sexe', mysql.CHAR(length=1), nullable=False),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('lieu_naissance', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('statut', mysql.VARCHAR(length=10), server_default=sa.text("'Actif'"), nullable=False),
    sa.CheckConstraint("`sexe` in ('M','F')", name=op.f('ck_eleve_sexe')),
    sa.CheckConstraint("`statut` in ('Actif','Inactif')", name=op.f('ck_eleve_statut')),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name=op.f('fk_eleve_etablissement'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], name=op.f('fk_eleve_parent'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_eleve_matricule_etablissement'), ['etablissement_id', 'matricule'], unique=True)

    op.create_table('creneau_horaire',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('libelle', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('heure_debut', mysql.TIME(), nullable=False),
    sa.Column('heure_fin', mysql.TIME(), nullable=False),
    sa.Column('ordre', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('creneau_horaire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_creneau_ordre'), ['ordre'], unique=True)

    op.create_table('parent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name=op.f('fk_parent_etablissement'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_parent_email'), ['email'], unique=True)

    op.create_table('note',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inscription_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('matiere_classe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sequence_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('valeur', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('absent', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('saisie_le', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('`valeur` is null or `valeur` >= 0 and `valeur` <= 20', name=op.f('ck_note_valeur')),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], name=op.f('fk_note_inscription'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matiere_classe_id'], ['matiere_classe.id'], name=op.f('fk_note_matiere_classe'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], name=op.f('fk_note_sequence'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_note'), ['inscription_id', 'matiere_classe_id', 'sequence_id'], unique=True)

    op.create_table('titulaire_classe',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('classe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('enseignant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('annee_scolaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], name=op.f('fk_titulaire_classe_annee_scolaire'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], name=op.f('fk_titulaire_classe_classe'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], name=op.f('fk_titulaire_classe_enseignant'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('titulaire_classe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_titulaire_classe_annee'), ['classe_id', 'annee_scolaire_id'], unique=True)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
